package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-29T22:11:02.549-05:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ISRVEntCliente")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.clienteentities.ObjectFactory.class})
public interface ISRVEntCliente {

    @WebMethod(operationName = "BuscarClienteOrden", action = "http://tempuri.org/ISRVEntCliente/BuscarClienteOrden")
    @Action(input = "http://tempuri.org/ISRVEntCliente/BuscarClienteOrden", output = "http://tempuri.org/ISRVEntCliente/BuscarClienteOrdenResponse")
    @RequestWrapper(localName = "BuscarClienteOrden", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarClienteOrden")
    @ResponseWrapper(localName = "BuscarClienteOrdenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarClienteOrdenResponse")
    @WebResult(name = "BuscarClienteOrdenResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.clienteentities.ClienteVTOrdenEntity buscarClienteOrden(
        @WebParam(name = "idOrden", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idOrden
    );

    @WebMethod(operationName = "NuevoCliente", action = "http://tempuri.org/ISRVEntCliente/NuevoCliente")
    @Action(input = "http://tempuri.org/ISRVEntCliente/NuevoCliente", output = "http://tempuri.org/ISRVEntCliente/NuevoClienteResponse")
    @RequestWrapper(localName = "NuevoCliente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NuevoCliente")
    @ResponseWrapper(localName = "NuevoClienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NuevoClienteResponse")
    @WebResult(name = "NuevoClienteResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer nuevoCliente(
        @WebParam(name = "CE", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.clienteentities.ClienteRequestEntity ce,
        @WebParam(name = "TE", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.clienteentities.TarjetaAddRequestEntity te
    );

    @WebMethod(operationName = "NuevaTarjetaOrden", action = "http://tempuri.org/ISRVEntCliente/NuevaTarjetaOrden")
    @Action(input = "http://tempuri.org/ISRVEntCliente/NuevaTarjetaOrden", output = "http://tempuri.org/ISRVEntCliente/NuevaTarjetaOrdenResponse")
    @RequestWrapper(localName = "NuevaTarjetaOrden", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NuevaTarjetaOrden")
    @ResponseWrapper(localName = "NuevaTarjetaOrdenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NuevaTarjetaOrdenResponse")
    @WebResult(name = "NuevaTarjetaOrdenResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean nuevaTarjetaOrden(
        @WebParam(name = "idOrden", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idOrden,
        @WebParam(name = "TE", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.clienteentities.TarjetaAddRequestEntity te
    );

    @WebMethod(operationName = "NuevoClienteBasico", action = "http://tempuri.org/ISRVEntCliente/NuevoClienteBasico")
    @Action(input = "http://tempuri.org/ISRVEntCliente/NuevoClienteBasico", output = "http://tempuri.org/ISRVEntCliente/NuevoClienteBasicoResponse")
    @RequestWrapper(localName = "NuevoClienteBasico", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NuevoClienteBasico")
    @ResponseWrapper(localName = "NuevoClienteBasicoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NuevoClienteBasicoResponse")
    @WebResult(name = "NuevoClienteBasicoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer nuevoClienteBasico(
        @WebParam(name = "CE", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.clienteentities.ClienteRequestEntity ce
    );

    @WebMethod(operationName = "BuscarClientesXIdProducto", action = "http://tempuri.org/ISRVEntCliente/BuscarClientesXIdProducto")
    @Action(input = "http://tempuri.org/ISRVEntCliente/BuscarClientesXIdProducto", output = "http://tempuri.org/ISRVEntCliente/BuscarClientesXIdProductoResponse")
    @RequestWrapper(localName = "BuscarClientesXIdProducto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarClientesXIdProducto")
    @ResponseWrapper(localName = "BuscarClientesXIdProductoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarClientesXIdProductoResponse")
    @WebResult(name = "BuscarClientesXIdProductoResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.clienteentities.ArrayOfClienteEntity buscarClientesXIdProducto(
        @WebParam(name = "idProducto", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idProducto
    );

    @WebMethod(operationName = "BuscarCliente", action = "http://tempuri.org/ISRVEntCliente/BuscarCliente")
    @Action(input = "http://tempuri.org/ISRVEntCliente/BuscarCliente", output = "http://tempuri.org/ISRVEntCliente/BuscarClienteResponse")
    @RequestWrapper(localName = "BuscarCliente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarCliente")
    @ResponseWrapper(localName = "BuscarClienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarClienteResponse")
    @WebResult(name = "BuscarClienteResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.clienteentities.ClienteEntity buscarCliente(
        @WebParam(name = "idCliente", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idCliente
    );

    @WebMethod(operationName = "BuscarClienteOrdenMasVendidas", action = "http://tempuri.org/ISRVEntCliente/BuscarClienteOrdenMasVendidas")
    @Action(input = "http://tempuri.org/ISRVEntCliente/BuscarClienteOrdenMasVendidas", output = "http://tempuri.org/ISRVEntCliente/BuscarClienteOrdenMasVendidasResponse")
    @RequestWrapper(localName = "BuscarClienteOrdenMasVendidas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarClienteOrdenMasVendidas")
    @ResponseWrapper(localName = "BuscarClienteOrdenMasVendidasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarClienteOrdenMasVendidasResponse")
    @WebResult(name = "BuscarClienteOrdenMasVendidasResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.clienteentities.ArrayOfClienteOrdenMasVendidasEntity buscarClienteOrdenMasVendidas(
        @WebParam(name = "fechaInicio", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaInicio,
        @WebParam(name = "fechaFin", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaFin
    );

    @WebMethod(operationName = "EditarClienteBasico", action = "http://tempuri.org/ISRVEntCliente/EditarClienteBasico")
    @Action(input = "http://tempuri.org/ISRVEntCliente/EditarClienteBasico", output = "http://tempuri.org/ISRVEntCliente/EditarClienteBasicoResponse")
    @RequestWrapper(localName = "EditarClienteBasico", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditarClienteBasico")
    @ResponseWrapper(localName = "EditarClienteBasicoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditarClienteBasicoResponse")
    @WebResult(name = "EditarClienteBasicoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer editarClienteBasico(
        @WebParam(name = "CE", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.clienteentities.ClienteModRequestEntity ce
    );

    @WebMethod(operationName = "BuscarClienteFull", action = "http://tempuri.org/ISRVEntCliente/BuscarClienteFull")
    @Action(input = "http://tempuri.org/ISRVEntCliente/BuscarClienteFull", output = "http://tempuri.org/ISRVEntCliente/BuscarClienteFullResponse")
    @RequestWrapper(localName = "BuscarClienteFull", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarClienteFull")
    @ResponseWrapper(localName = "BuscarClienteFullResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarClienteFullResponse")
    @WebResult(name = "BuscarClienteFullResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.clienteentities.ClienteFullEntity buscarClienteFull(
        @WebParam(name = "idCliente", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idCliente
    );

    @WebMethod(operationName = "EditarCliente", action = "http://tempuri.org/ISRVEntCliente/EditarCliente")
    @Action(input = "http://tempuri.org/ISRVEntCliente/EditarCliente", output = "http://tempuri.org/ISRVEntCliente/EditarClienteResponse")
    @RequestWrapper(localName = "EditarCliente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditarCliente")
    @ResponseWrapper(localName = "EditarClienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditarClienteResponse")
    @WebResult(name = "EditarClienteResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer editarCliente(
        @WebParam(name = "CE", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.clienteentities.ClienteModRequestEntity ce,
        @WebParam(name = "TE", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.clienteentities.TarjetaModRequestEntity te
    );
}
