package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-30T19:44:26.284-05:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ISrvEntOrden")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.ordenentities.ObjectFactory.class})
public interface ISrvEntOrden {

    @WebMethod(operationName = "BuscarOrdenesAbiertas", action = "http://tempuri.org/ISrvEntOrden/BuscarOrdenesAbiertas")
    @Action(input = "http://tempuri.org/ISrvEntOrden/BuscarOrdenesAbiertas", output = "http://tempuri.org/ISrvEntOrden/BuscarOrdenesAbiertasResponse")
    @RequestWrapper(localName = "BuscarOrdenesAbiertas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarOrdenesAbiertas")
    @ResponseWrapper(localName = "BuscarOrdenesAbiertasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarOrdenesAbiertasResponse")
    @WebResult(name = "BuscarOrdenesAbiertasResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ordenentities.ArrayOfOrdenesAbiertasEntity buscarOrdenesAbiertas();

    @WebMethod(operationName = "NuevaOrden", action = "http://tempuri.org/ISrvEntOrden/NuevaOrden")
    @Action(input = "http://tempuri.org/ISrvEntOrden/NuevaOrden", output = "http://tempuri.org/ISrvEntOrden/NuevaOrdenResponse")
    @RequestWrapper(localName = "NuevaOrden", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NuevaOrden")
    @ResponseWrapper(localName = "NuevaOrdenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NuevaOrdenResponse")
    @WebResult(name = "NuevaOrdenResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Integer nuevaOrden(
        @WebParam(name = "OE", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ordenentities.OrdenRequestEntity oe,
        @WebParam(name = "ODES", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas._2004._07.ordenentities.ArrayOfOrdenDetalleRequestEntity odes
    );

    @WebMethod(operationName = "EditarOrdenProveedorMensajeria", action = "http://tempuri.org/ISrvEntOrden/EditarOrdenProveedorMensajeria")
    @Action(input = "http://tempuri.org/ISrvEntOrden/EditarOrdenProveedorMensajeria", output = "http://tempuri.org/ISrvEntOrden/EditarOrdenProveedorMensajeriaResponse")
    @RequestWrapper(localName = "EditarOrdenProveedorMensajeria", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditarOrdenProveedorMensajeria")
    @ResponseWrapper(localName = "EditarOrdenProveedorMensajeriaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditarOrdenProveedorMensajeriaResponse")
    @WebResult(name = "EditarOrdenProveedorMensajeriaResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean editarOrdenProveedorMensajeria(
        @WebParam(name = "idOrden", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idOrden
    );

    @WebMethod(operationName = "EditarOrdenEstado", action = "http://tempuri.org/ISrvEntOrden/EditarOrdenEstado")
    @Action(input = "http://tempuri.org/ISrvEntOrden/EditarOrdenEstado", output = "http://tempuri.org/ISrvEntOrden/EditarOrdenEstadoResponse")
    @RequestWrapper(localName = "EditarOrdenEstado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditarOrdenEstado")
    @ResponseWrapper(localName = "EditarOrdenEstadoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditarOrdenEstadoResponse")
    @WebResult(name = "EditarOrdenEstadoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean editarOrdenEstado(
        @WebParam(name = "idOrden", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idOrden,
        @WebParam(name = "idEstado", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idEstado,
        @WebParam(name = "Asesor", targetNamespace = "http://tempuri.org/")
        java.lang.String asesor
    );

    @WebMethod(operationName = "BuscarOrdenCliente", action = "http://tempuri.org/ISrvEntOrden/BuscarOrdenCliente")
    @Action(input = "http://tempuri.org/ISrvEntOrden/BuscarOrdenCliente", output = "http://tempuri.org/ISrvEntOrden/BuscarOrdenClienteResponse")
    @RequestWrapper(localName = "BuscarOrdenCliente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarOrdenCliente")
    @ResponseWrapper(localName = "BuscarOrdenClienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarOrdenClienteResponse")
    @WebResult(name = "BuscarOrdenClienteResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ordenentities.ArrayOfOrdenEntity buscarOrdenCliente(
        @WebParam(name = "idCliente", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idCliente
    );

    @WebMethod(operationName = "EditarOrdenProveedorMensajeriaEstado", action = "http://tempuri.org/ISrvEntOrden/EditarOrdenProveedorMensajeriaEstado")
    @Action(input = "http://tempuri.org/ISrvEntOrden/EditarOrdenProveedorMensajeriaEstado", output = "http://tempuri.org/ISrvEntOrden/EditarOrdenProveedorMensajeriaEstadoResponse")
    @RequestWrapper(localName = "EditarOrdenProveedorMensajeriaEstado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditarOrdenProveedorMensajeriaEstado")
    @ResponseWrapper(localName = "EditarOrdenProveedorMensajeriaEstadoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditarOrdenProveedorMensajeriaEstadoResponse")
    @WebResult(name = "EditarOrdenProveedorMensajeriaEstadoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean editarOrdenProveedorMensajeriaEstado(
        @WebParam(name = "idOrden", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idOrden,
        @WebParam(name = "proveedorMensajeria", targetNamespace = "http://tempuri.org/")
        java.lang.String proveedorMensajeria,
        @WebParam(name = "estado", targetNamespace = "http://tempuri.org/")
        java.lang.String estado
    );

    @WebMethod(operationName = "BuscarOrdenesCerradasXMes", action = "http://tempuri.org/ISrvEntOrden/BuscarOrdenesCerradasXMes")
    @Action(input = "http://tempuri.org/ISrvEntOrden/BuscarOrdenesCerradasXMes", output = "http://tempuri.org/ISrvEntOrden/BuscarOrdenesCerradasXMesResponse")
    @RequestWrapper(localName = "BuscarOrdenesCerradasXMes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarOrdenesCerradasXMes")
    @ResponseWrapper(localName = "BuscarOrdenesCerradasXMesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarOrdenesCerradasXMesResponse")
    @WebResult(name = "BuscarOrdenesCerradasXMesResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ordenentities.ArrayOfOrdenesCerradasXMesEntity buscarOrdenesCerradasXMes();

    @WebMethod(operationName = "BuscarOrdenDetalle", action = "http://tempuri.org/ISrvEntOrden/BuscarOrdenDetalle")
    @Action(input = "http://tempuri.org/ISrvEntOrden/BuscarOrdenDetalle", output = "http://tempuri.org/ISrvEntOrden/BuscarOrdenDetalleResponse")
    @RequestWrapper(localName = "BuscarOrdenDetalle", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarOrdenDetalle")
    @ResponseWrapper(localName = "BuscarOrdenDetalleResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarOrdenDetalleResponse")
    @WebResult(name = "BuscarOrdenDetalleResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ordenentities.ArrayOfOrdenDetalleEntity buscarOrdenDetalle(
        @WebParam(name = "idOrden", targetNamespace = "http://tempuri.org/")
        java.lang.Integer idOrden
    );

    @WebMethod(operationName = "BuscarOrdenesCerradas", action = "http://tempuri.org/ISrvEntOrden/BuscarOrdenesCerradas")
    @Action(input = "http://tempuri.org/ISrvEntOrden/BuscarOrdenesCerradas", output = "http://tempuri.org/ISrvEntOrden/BuscarOrdenesCerradasResponse")
    @RequestWrapper(localName = "BuscarOrdenesCerradas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarOrdenesCerradas")
    @ResponseWrapper(localName = "BuscarOrdenesCerradasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuscarOrdenesCerradasResponse")
    @WebResult(name = "BuscarOrdenesCerradasResult", targetNamespace = "http://tempuri.org/")
    public org.datacontract.schemas._2004._07.ordenentities.ArrayOfOrdenesCerradasEntity buscarOrdenesCerradas(
        @WebParam(name = "fechaInicio", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaInicio,
        @WebParam(name = "fechaFin", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaFin
    );
}
