package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-30T19:44:26.300-05:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "SrvEntOrden", 
                  wsdlLocation = "http://25.13.58.186:1003/SrvEntOrden.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class SrvEntOrden extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SrvEntOrden");
    public final static QName BasicHttpBindingISrvEntOrden = new QName("http://tempuri.org/", "BasicHttpBinding_ISrvEntOrden");
    static {
        URL url = null;
        try {
            url = new URL("http://25.13.58.186:1003/SrvEntOrden.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SrvEntOrden.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://25.13.58.186:1003/SrvEntOrden.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SrvEntOrden(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SrvEntOrden(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrvEntOrden() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SrvEntOrden(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SrvEntOrden(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SrvEntOrden(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ISrvEntOrden
     */
    @WebEndpoint(name = "BasicHttpBinding_ISrvEntOrden")
    public ISrvEntOrden getBasicHttpBindingISrvEntOrden() {
        return super.getPort(BasicHttpBindingISrvEntOrden, ISrvEntOrden.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISrvEntOrden
     */
    @WebEndpoint(name = "BasicHttpBinding_ISrvEntOrden")
    public ISrvEntOrden getBasicHttpBindingISrvEntOrden(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingISrvEntOrden, ISrvEntOrden.class, features);
    }

}
