package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-29T22:11:02.649-05:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "SRVEntCliente", 
                  wsdlLocation = "http://25.13.58.186:1002/SRVEntCliente.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class SRVEntCliente extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SRVEntCliente");
    public final static QName BasicHttpBindingISRVEntCliente = new QName("http://tempuri.org/", "BasicHttpBinding_ISRVEntCliente");
    static {
        URL url = null;
        try {
            url = new URL("http://25.13.58.186:1002/SRVEntCliente.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SRVEntCliente.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://25.13.58.186:1002/SRVEntCliente.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SRVEntCliente(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SRVEntCliente(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SRVEntCliente() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SRVEntCliente(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SRVEntCliente(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SRVEntCliente(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ISRVEntCliente
     */
    @WebEndpoint(name = "BasicHttpBinding_ISRVEntCliente")
    public ISRVEntCliente getBasicHttpBindingISRVEntCliente() {
        return super.getPort(BasicHttpBindingISRVEntCliente, ISRVEntCliente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISRVEntCliente
     */
    @WebEndpoint(name = "BasicHttpBinding_ISRVEntCliente")
    public ISRVEntCliente getBasicHttpBindingISRVEntCliente(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingISRVEntCliente, ISRVEntCliente.class, features);
    }

}
