package com.sony.sonyordenarcotizacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-30T18:35:27.321-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "SonyOrdenarCotizacion", 
                  wsdlLocation = "file:/C:/WorkSpaceKall/SonyOrdenarCotizacion/WebContent/SonyOrdenarCotizacion.wsdl",
                  targetNamespace = "http://www.sony.com/SonyOrdenarCotizacion/") 
public class SonyOrdenarCotizacion extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sony.com/SonyOrdenarCotizacion/", "SonyOrdenarCotizacion");
    public final static QName SonyOrderService = new QName("http://www.sony.com/SonyOrdenarCotizacion/", "SonyOrderService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/WorkSpaceKall/SonyOrdenarCotizacion/WebContent/SonyOrdenarCotizacion.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SonyOrdenarCotizacion.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/WorkSpaceKall/SonyOrdenarCotizacion/WebContent/SonyOrdenarCotizacion.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SonyOrdenarCotizacion(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SonyOrdenarCotizacion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SonyOrdenarCotizacion() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SonyOrdenarCotizacion(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SonyOrdenarCotizacion(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SonyOrdenarCotizacion(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SonyOrderService
     */
    @WebEndpoint(name = "SonyOrderService")
    public SonyOrderService getSonyOrderService() {
        return super.getPort(SonyOrderService, SonyOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SonyOrderService
     */
    @WebEndpoint(name = "SonyOrderService")
    public SonyOrderService getSonyOrderService(WebServiceFeature... features) {
        return super.getPort(SonyOrderService, SonyOrderService.class, features);
    }

}
