package org.rapidservice.rapidservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-02T22:01:24.204-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "RapidService", 
                  wsdlLocation = "file:/C:/WorkSpaceKall/RapidService/WebContent/RapidService.wsdl",
                  targetNamespace = "http://www.rapidservice.org/RapidService/") 
public class RapidService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.rapidservice.org/RapidService/", "RapidService");
    public final static QName RapidServiceSOAP = new QName("http://www.rapidservice.org/RapidService/", "RapidServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/WorkSpaceKall/RapidService/WebContent/RapidService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RapidService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/WorkSpaceKall/RapidService/WebContent/RapidService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RapidService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RapidService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RapidService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RapidService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RapidService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RapidService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RapidService
     */
    @WebEndpoint(name = "RapidServiceSOAP")
    public RapidService getRapidServiceSOAP() {
        return super.getPort(RapidServiceSOAP, RapidService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RapidService
     */
    @WebEndpoint(name = "RapidServiceSOAP")
    public RapidService getRapidServiceSOAP(WebServiceFeature... features) {
        return super.getPort(RapidServiceSOAP, RapidService.class, features);
    }

}
