package org.rapidservice.rapidservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-02T22:01:24.189-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.rapidservice.org/RapidService/", name = "RapidService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RapidService {

    @WebMethod(action = "http://www.rapidservice.org/RapidService/processQuote")
    @WebResult(name = "processQuoteResponseElement", targetNamespace = "http://www.rapidservice.org/RapidService/", partName = "parameters")
    public ProcessQuoteResponseElement processQuote(
        @WebParam(partName = "parameters", name = "processQuoteElement", targetNamespace = "http://www.rapidservice.org/RapidService/")
        ProcessQuoteElement parameters
    );

    @WebMethod(action = "http://www.rapidservice.org/RapidService/orderQuoute")
    @WebResult(name = "orderQuouteResponseElement", targetNamespace = "http://www.rapidservice.org/RapidService/", partName = "parameters")
    public OrderQuouteResponseElement orderQuoute(
        @WebParam(partName = "parameters", name = "orderQuouteElement", targetNamespace = "http://www.rapidservice.org/RapidService/")
        OrderQuouteElement parameters
    );
}
