package com.oracle.xmlns.sonyquoteservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-02T22:16:34.355-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/SonyQuoteService", name = "SonyQuoteService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SonyQuoteService {

    @WebMethod(action = "http://www.sony.com/orderQuoute")
    @WebResult(name = "SonyQuoteServiceProcessResponse", targetNamespace = "http://xmlns.oracle.com/SonyQuoteService", partName = "payload")
    public SonyQuoteServiceProcessResponse initiate(
        @WebParam(partName = "payload", name = "SonyQuoteServiceProcessRequest", targetNamespace = "http://xmlns.oracle.com/SonyQuoteService")
        SonyQuoteServiceProcessRequest payload
    );
}
