package com.validar.validaciontarjetacredito;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-30T11:29:10.840-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.validar.com/ValidacionTarjetaCredito/", name = "ValidateCreditCard")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ValidateCreditCard {

    @WebMethod(operationName = "VerifyCC", action = "http://www.validar.com/VerifyCC")
    @WebResult(name = "valid", targetNamespace = "http://www.validar.com/ValidacionTarjetaCredito/", partName = "valid")
    public boolean verifyCC(
        @WebParam(partName = "creditCard", name = "creditCard", targetNamespace = "http://www.validar.com/ValidacionTarjetaCredito/")
        CreditCard creditCard
    ) throws CreditCardValidationFaultMessage;
}
