package co.com.kallsonys.oms.crud;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBoxGroup;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

import co.com.kallsonys.oms.backend.data.Availability;
import co.com.kallsonys.oms.backend.data.Category;
import co.com.kallsonys.oms.backend.entity.Categoria;
import co.com.kallsonys.oms.backend.entity.Fabricante;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProductFormDesign extends CssLayout {
	protected TextField codigo;
    protected TextField productName;
    protected TextField price;
    protected TextField valorDescuento;
    protected TextField stockCount;
    protected TextField urlImagen;
    protected TextArea descripcion;
//    protected ComboBox<Availability> availability;
//    protected CheckBoxGroup<Category> category;
    protected ComboBox<Categoria> categoria;
    protected ComboBox<Fabricante> fabricante;
    protected Button save;
    protected Button discard;
    protected Button cancel;
    protected Button delete;

    public ProductFormDesign() {
        Design.read(this);
    }
}